-- =============================================================================
-- SNOWFLAKE — Destination Setup for Openflow 2-Table Incremental POC
-- Run as ACCOUNTADMIN
-- =============================================================================

CREATE DATABASE IF NOT EXISTS OPENFLOW_SQLSERVER_POC;
CREATE SCHEMA IF NOT EXISTS OPENFLOW_SQLSERVER_POC.INCREMENTAL_POC;

CREATE USER IF NOT EXISTS OPENFLOW_SQLSERVER_SVC
  TYPE = SERVICE
  COMMENT = 'Service user for Openflow SQL Server connector';

CREATE ROLE IF NOT EXISTS OPENFLOW_SQLSERVER_ROLE;
GRANT ROLE OPENFLOW_SQLSERVER_ROLE TO USER OPENFLOW_SQLSERVER_SVC;
GRANT USAGE ON DATABASE OPENFLOW_SQLSERVER_POC TO ROLE OPENFLOW_SQLSERVER_ROLE;
GRANT CREATE SCHEMA ON DATABASE OPENFLOW_SQLSERVER_POC TO ROLE OPENFLOW_SQLSERVER_ROLE;
GRANT ALL ON SCHEMA OPENFLOW_SQLSERVER_POC.INCREMENTAL_POC TO ROLE OPENFLOW_SQLSERVER_ROLE;

CREATE WAREHOUSE IF NOT EXISTS OPENFLOW_SQLSERVER_WH WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;
GRANT USAGE, OPERATE ON WAREHOUSE OPENFLOW_SQLSERVER_WH TO ROLE OPENFLOW_SQLSERVER_ROLE;

-- After running generate-keys.sh, paste the public key here:
-- ALTER USER OPENFLOW_SQLSERVER_SVC SET RSA_PUBLIC_KEY = '<paste-key-without-headers>';
